version: '3.8'

services:
  
  db:
    build:
      context: ./
      dockerfile: db.Dockerfile
    restart: always
    # user: "${UserID}:${GroupID}"
    volumes:
      - ./pgdata:/var/lib/postgres:Z
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    networks:
      - intranet

networks:
  intranet:
  
volumes:
  pgdata: